[build]
  command = "npm --prefix backend run build"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200